### ISSUE TITLE
how to interpret CircleCI FAIL and XFAIL

### ISSUE THREAD

**Issue by mrneont** [afni/afni#283]
@leej3 

Let's say, hypothetically, that I get the following failures and xfailures from CircleCI---which ones are lethal for the testing?  Just "FAILED", or also "XFAILED"?
```
=========================== short test summary info ============================

FAILED scripts/test_python_style.py::test_for_unblackened - ValueError: The c...

FAILED scripts/test_testing_script_functionality.py::test_run_tests_with_args[params1]

SKIPPED [1] scripts/test_3dAllineate.py:17: reason=The comparison of to affines should use the expected distance of movement for a point drawn from a 3D cloud.

SKIPPED [2] scripts/test_3dSkullStrip.py:11: May cause a graphics race condition. Not bothing to test further.

SKIPPED [1] scripts/test_****_proc.py:16: Not working. May have to rethink text diffing a little.

SKIPPED [1] scripts/test_****_proc.py:67: Not working. May have to rethink text diffing a little.

SKIPPED [1] scripts/test_python_imports.py:15: this is implemented in a shell script. ****py should be imported from

SKIPPED [1] scripts/test_testing_script_functionality.py:412: Failed to find a running docker service.

XFAIL scripts/test_help_messages.py::test_prog_list_helps

XFAIL scripts/test_ptaylor.py::test_3dTrackID_DET

XFAIL scripts/test_ptaylor.py::test_3dTrackID_PROB

XFAIL scripts/test_ptaylor.py::test_3dNetCorr

= 2 failed, 157 passed, 7 skipped, 4 xfailed, 5 warnings in 620.03s (0:10:20) ==


Exited with code exit status 1

CircleCI received exit code 1
```

Also, what does "test for unblackened" mean?  I have tried running the Python program "black":
https://pypi.org/project/black/
... on the offending test_testing_script_functionality.py program, and *many* lines get changed, more than ones just recently changed (when testing was working).   I see this is what it is supposed to mean:
`ValueError: The coding style in some of the python files does not conform with the projects. Specifically we use black and pep8 (but with a max line length of 88 characters). Files can be corrected with the tools autopep8 and black. For more info see https://github.com/ambv/black and https://github.com/hhatto/autopep8`
... but I also ran black on other programs in that tests/scripts/ directory, and black would want to change many of them---however, there aren't failures showing up.  What does the "black" program actually test (and does "black" conflict with pep8 in some cases?)?  And where can I see what is *actually* a formatting error (NB: I assume no code is failing, it is just a mismatch with the program's choice of what it should look like)?

Finally, how can I see what "params1" is in the failure here:
`test_run_tests_with_args[params1]`
?

Thanks.

**Comment by mrneont** [comment]
And an update:

There should just be 1 FAILED message now;  the 
`scripts/test_python_style.py::test_for_unblackened ....`
one should be fixed by this commit:
https://github.com/afni/afni/commit/f61001c6c76ab3daf7c967eb2db03d37e1b81075

The remaining FAILURE is:
`FAILED scripts/test_testing_script_functionality.py::test_run_tests_with_args[params1]`
... and the same XFAIL occur.

Note that I did run the same set of ptaylor tests on my computer (using my tcsh script that was used to create test_ptaylor.py), and those show no differences in the volumetric outputs for any ptaylor programs.  So, I am not sure how to interpret the XFAIL.

**Comment by leej3** [comment]
The description of Xfail is [here](https://docs.pytest.org/en/6.2.x/skipping.html#xfail-mark-test-functions-as-expected-to-fail)... would be great to pass but they are expected to fail... typically because of a known bug or a missing feature.

> unblackened

That is my wording. Basically  "black" runs on a given file and it causes reformatting to occur. I enforced black on all python files in tests.  You can turn that off if you like. I just found that using black to autoformat code made me spend a lot less time/mental energy on style. I implemented a git hook that you can use that auto formats the code when one commits it.There's also [pre-commit](https://pre-commit.com/hooks.html). Whatever suits best...

>  and many lines get changed

This coding style is only forced in tests... outside of that would have some drastic reformatting so that is not feasible. Regarding such an event occuring to a file with the tests directory: you need to be careful about the version of black installed. The reformatting behavior changes across versions. Generally you pick a version, cling to it for formatting reproducibility, and then make a leap to a more recent version at a later date. Such changes are happening less and less frequently as the tool has matured.

> What does the "black" program actually test

I am using it as a test here but it is more usefully regarded as an algorithmic solution to homogenous code style in a code-base.

> does "black" conflict with pep8 in some cases?

The short answer is that black is pep8 compliant. It's not that simple though. Black, by default uses 88 chars per line: this works very nicely but does violate pep8. In addition, black is just a reformatting tool... it tries its best but there are some patterns that it simply can't handle... in those cases it just leaves it untouched. So running black will reduce the number of pep8 violation but it won't get you the whole way. There is a tool called autopep8. I prefer black and they largely have overlapping fixes. autopep8 also has a limit in its ability to get you to code that has no issues with a pep8 linter (like pyflakes or something like that).

>  I assume no code is failing, it is just a mismatch with the program's choice of what it should look like

Correct. The diagnosis would be that the code currently has lines that change when running the version of black in the docker container. If you were to use that version locally you would see those restricted set of changes. Black formats the whole directory very quickly in the way I have used it in the test. If you wish to keep this testing behavoir, don't mind  making the test slower, but errors far more useful you could run black on each file individual, collecting the diffs when they exist and raising the errors with those diffs.

> Finally, how can I see what "params1" is in the failure here: test_run_tests_with_args[params1]

If you run these tests locally you can use pdb to step through the code an inspect the values of the variables. You can also see it in the source code though. I worked through pytest's approach to running tests with different parameters with @afni-dglen. in this case it is the 2nd set of parameters that are passed to the function: https://github.com/afni/afni/blob/f61001c6c76ab3daf7c967eb2db03d37e1b81075/tests/scripts/test_testing_script_functionality.py#L700


> those show no differences in the volumetric outputs for any ptaylor programs. So, I am not sure how to interpret the XFAIL.

I think this might be that the file formats there do not have a diffing strategy defined for them. I implemented one for text files, log files, 3d volumes, binary files (direct byte matching which is rather useless), and 1d files. Suma formats etc didn't get finished. You could take a look at the sort of thing done for 1d files and consider implementing a diffing strategy for those files. I suspect you could use the [niml parsing code](https://github.com/afni/afni/blob/master/src/python_scripts/afnipy/niml_parsing.py) to get a somewhat useful representation of the data in python and implement something... or pipe the output files through some afni tools to render the output in a file format that has diffing implemented for it... maybe some summary statistic in a text file or something like that. Or you could explicitly ignore all output files that are in an unsupported format (I believe passing the files to [this argument](https://github.com/afni/afni/blob/f61001c6c76ab3daf7c967eb2db03d37e1b81075/tests/afni_test_utils/tools.py#L804) should achieve that)

**Comment by mrneont** [comment]
Hi, John-

Thanks for the pointer about "xfail" and what it means.  It sounds like the "expected fail" for these programs (3dTrackID in DET and PROB mode, and 3dNetCorr) is just because there there isn't a test for their outputs (even though they do make volumetric outputs, and ASCII text, as well as *.niml* files).  Perhaps their SUMA dependencies means that the Cmake build can't handle them well?  Anyways, it sounds like these aren't critical errors, leading to an overall "fail" result, which is what I am trying to alleviate at this moment.  I will leave deeper investigation for another day.

Re. testing with the Python program "black":  With the version I used via conda (version 19.10b0), I tried running it both without opts and with "--py36".  In each case, every program in afni/tests/scripts/*py failed.  It seems odd that a "standard format of python" would differ by Python version or by program version so strongly.  The fact that it is OK with longer lines that pep8 makes it difficult for me to see how it is compatible with pep8, then, by definition...  Most changes the "black" program made were in fact to un-multiline, making very long lines (some even >80 chars).  I think we will probably turn this off, since it doesn't sound stable---again, because every program in that directory actually fails this testing with current "black" program function (and surely they would have only make a "better" or more standard version of the program, so we should use what is more modern if we want to use it?).  But we also did fix the failure due to that program check, so this is not a critical issue at the moment to get the tests working.

So, this mainly leaves me the question of why "test_run_tests_with_args[params1]" is failing.  And note:  something happened recently to lead this into being a failure (this isn't a long-running thing), so that is what is confusing me.  I will try to dust off my ability to run locally with PDB...
And by "second", that means [1]th set, so this
```
{
            "image_name": "an_image",
            "only_use_local": False,
            "source_mode": "test-data-volume",
        },
```
?

Thanks.

**Comment by leej3** [comment]
> that the Cmake build can't handle them well

It’s the output differ class that handle them. It just not implemented. As you said, it’s not the cause of the failure. And the tests are still running the tools and checking that a non zero exit status occurs... so they’re provided some benefit in that state. 

> [1]th

correct. I think it’s a test of the coverage functionality though and not what you have quoted above. I’d delete the parameters that test the coverage functionality of the testing tool. I’m guessing that no longer works as expected so is causing the failure.

**Comment by mrneont** [comment]
Thanks, I tried that on this branch:
https://github.com/afni/afni/commit/55b52db87b1cc773accd55beaad3b1f18befce26
... but I get the same failure message.

**Comment by mrneont** [comment]
... and actually, 
```
if params["test_case"] == "with_coverage":
     pytest.skip("coverage testing broken")
```
did reduce one FAILED;  removing the echo within the codecov execution (and comments in the Python code) apparently removed another one.

**Comment by mrneont** [comment]
OK, all currently-occurring failures seem to have been relegated at this point.

In addition to the above "if params ..." suggestion, we also had to remove all comments from the section around codecov (within the python), and not have it even echo a warning in the terminal:
https://github.com/afni/afni/commit/f121b9811f56e7b73a8bd5029bc36c4a2cca79a8

Even after this, we got a new failure, some kind of change with what CircleCI wanted from Docker, to this fixed on new failure message that popped up:
https://github.com/afni/afni/commit/a91ba89fe39037ea5a1c6c64a846d046cf609013

Occasionally, we get failures about Xvfb---it seems not all GUI output text is captured, because something times out doesn't wait long enough on the CircleCI server.  However, this does not always occur, so it is hard to troubleshoot.  If this occurs a lot, then we might have to extend timeout/sleep values within the code, perhaps.

thanks, @leej3, for your suggestions in troubleshooting these different failure messages.  (Re. the other/slightly related issue of updating the test framework---hopefully someone at datalad can try to help us troubleshoot those datalad failures and/or git-annex version issues, rather than us needing to disable tests.)

**Comment by leej3** [comment]
> Even after this, we got a new failure, some kind of change with what CircleCI wanted from Docker

Yep that just looks like a deprecation of their API, work around looks good. 

> Occasionally, we get failures about Xvfb---it seems not all GUI output text is captured, because something times out doesn't wait long enough on the CircleCI server

Yes, these issues are exceptionally difficult to debug. After many iterations I arrived at the current Xvfb/subprocess execution setup. The problem would be greatly alleviated if suma were to raise non-zero exit codes on failure. Without that there is a whole set of conditions that need to be taken into consideration. It is a mixture of the nuances of Xvfb usage (the tests for this are instructive: https://github.com/afni/afni/blob/master/tests/scripts/test_guis.py) as well as trying to figure out the most robust strategy for subprocess execution with the heterogeneous error behavior of the various tools in the suite (these tests give a sense of what the scenarios supported: https://github.com/afni/afni/blob/7bc375964a0a54323447842d6564a536e045476e/tests/scripts/test_testing_script_functionality.py#L171-L213)
