### ISSUE TITLE
Update 3dcalc to handle extreme values

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#301]
3dcalc could be updated to [address this issue](https://github.com/vsoch/TtoZ)

**Comment by mrneont** [comment]
Hi, @neurolabusc -

Thanks for pointing this out.  I guess as study sample sizes increase, one might run into these large statistic values more often.

One thing to note, I was trying to understand what that cited github page means when describing some of the displayed images.  Specifically, they write that 3dcalc's output set of values "extends to a density of 2.0 due to the number of zeros that are replaced to prevent error."  I don't think that is the case---and unfortunately it makes it sound like 3dcalc is doing something very erroneous, which it is not.

I downloaded their "original tstat", which is masked to cover a brain region with t-stat values (DF = 484); the masked region covers about a third of the FOV, and outside of this the values are 0.  I ran this dataset through 3dcalc, using their same command, to get Zstats from 3dcalc.  Note that as the number of degrees of freedom (DF) of the t-stat approach infinity, the t-stat distribution approaches the Z-stat distribution---which means that as DF becomes very large, the t-stat values are very similar to the Z-stat ones.  In this case, DF=484 is *quite* large, but there are still some small differences---fine, that is to be expected.  Finally, I downloaded their Hughett's t-to-z tranform "ttz" dataset.  

I made 2 histograms:  plotting the values when *no brainmasking is applied to any dset* (left panel), and plotting them *when brainmasking is applied to each*:
![plot_3line_df-484](https://user-images.githubusercontent.com/9322171/131774430-e0c41175-16bb-4d30-bc80-2c899a36b895.png)
I plotted the red (orig t-stat) and blue (3dcalc z-stat) values in translucent lines---where they overlap strongly, one gets purple.  The Hughett-zstat values are overlaid in green dashed lines.  In the left panel, **all** datasets have a big spike at stat=0, simply because there is no masking applied to the underlying dataset---it is *not* because 3dcalc (or any other program) is replacing zeros to avoid error.  (And the spike at zero is the same height for all three datasets---here is the same image zoomed out, and ones sees the blue+red making purple and the dotted green line present:
![plot_3lines_df-484_zoomed_out](https://user-images.githubusercontent.com/9322171/131775969-bc0fc055-32b6-4804-80d8-a439b422d91a.png)
When you look at the right panel (going back to the non-zoomed out image), all the lines match in the same, but the big feature at stat=0 is gone, verifying this.  Unfortunately, it seems like the cited github page did not compared masked-with-masked across all datasets, and so misidentified the reason for the spike at zero in the one plot.

Now, the noticeable difference in 3dcalc's values are that, while the agreement is excellent for the wide middle region, all of a sudden at Z=-13 there is a big vertical feature, as well as at Z=13.  This happens because 3dcalc is not outputting any Z-stat with magnitude >13---there is a floor and a ceiling, respectively, on the output value.  The size of the spike in each case is the same as the area of the tail extending outward in the t-stat distribution--again, the conversion of those output Z-stat values was capped at magnitude=13.  Indeed, the point of the Hughett algorithm is to avoid needing to do this (the capping is due to precision in floats, which NIFTI and BRIK/HEAD dsets use), and this **is** a useful thing to consider.

**Comment by mrneont** [comment]
... And if anyone wants how I made the distributions that are plotted, I dumped them to text files with the following:

```
#!/bin/tcsh

set dset_tstat = tfMRI_LANGUAGE_STORY.nii_tstat1.nii.gz
set ndof       = 484
set dset_zstat = zstat_afni_ndof_${ndof}.nii.gz     # zstat from 3dcalc
set dset_ttz   = zstat_ttz.nii                      # zstat from github TTZ

# make a mask, for use later
3dcalc                                               \
    -overwrite                                       \
    -a       ${dset_tstat}                           \
    -expr    'bool(a)'                               \
    -prefix  mask.nii.gz

# calc Zstat conversion
3dcalc                                               \
    -overwrite                                       \
    -a       ${dset_tstat}                           \
    -expr    "fitt_t2z (a,${ndof})"                  \
    -prefix  ${dset_zstat}                           \
    -float

# dump t-stat values to a text file, both masked and unmasked
3dmaskdump                                           \
    -noijk                                           \
    ${dset_tstat}                                    \
    > orig_tstat_df-${ndof}_nomask
3dmaskdump                                           \
    -noijk                                           \
    -mask mask.nii.gz                                \
    ${dset_tstat}                                    \
    > orig_tstat_df-${ndof}_mskd

# dump t-stat values to a text file, both masked and unmasked
3dmaskdump                                           \
    -noijk                                           \
    ${dset_zstat}                                    \
    > afni_zstat_nomask
3dmaskdump                                           \
    -noijk                                           \
    -mask mask.nii.gz                                \
    ${dset_zstat}                                    \
    > afni_zstat_mskd

# dump t-stat values to a text file, both masked and unmasked
3dmaskdump                                           \
    -noijk                                           \
    ${dset_ttz}                                      \
    > ttz_zstat_nomask
3dmaskdump                                           \
    -noijk                                           \
    -mask mask.nii.gz                                \
    ${dset_ttz}                                      \
    > ttz_zstat_mskd
```

... and then used Python+matplotlib to plot the histograms.
