### ISSUE TITLE
thd_euler_dist.c query

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#322]
@mrneont I have created anisotropic validation datasets to evaluate Euclidean Distance Transform (EDT). Part of my motivation was the slow performance of FSL's distance map, but the other was your recent work with thd_euler_dist.c to handle anisotropic images. 

Based on [other projects](https://github.com/seung-lab/euclidean-distance-transform-3d) I had assumed that handling anisotropic images was a bit tricky. However, your solution of warping inputs to unity prior to each pass and then transforming back seems insanely simple. 

Here is my [validation dataset](https://github.com/neurolabusc/distancemap)

My one question is regarding your permuting of axis and the code comment [to avoid pathology in the EDT alg (that miiiight have only existed in earlier calc method, but it still makes sense to do---why not?)](https://github.com/afni/afni/blob/a33c64ef809bb54e7002c52d2206a61722837b94/src/thd_euler_dist.c#L205). In my code, I omit this step, and I appear to get precise results regardless of the order of the anisotropy (e.g. the sample image i211 vs i112 where either the first or third dimension has low resolution). 

Do you have any examples you can share that exhibited this pathology, and can we confirm that your revised algorithm is robust? Your solution seems so deceptively simple that I am shocked it works. However, I can not find any counter examples that require a more complicated solution.

**Comment by mrneont** [comment]
@neurolabusc :

To the other question raised here:  is it necessary/useful to proceed in order of max->min voxel dimension? (This was in reference to a note in thd_euler_dist.c.)

I've now looked back into this in more detail.  The original motivation to sort the order of axis traversal by voxel edge length (starting along the axis with longest edges) was because not doing so caused an error in some specific case(s) in the early, generalized form of multi-ROI distance mapping that I implemented in Python, before programming the same/similar thing in C.  Having checked a few different cases in the C code, there does not seem to be a problem (so, squashing the bug, or just implementing it better, removed the need for doing this ordering.)  So there doesn't appear to be a bug-related reason for doing so.

I *then* thought it the order of axis traversal make a difference for speed of calculation:  the amount of parabola updates might be affected by the order of traversing the matrix, esp. when there are large empty areas.  So, I tried a few combinations of datasets, always reading through in axis order 0, 1, 2 (dset orients were uniformly RAI), for pairs of datasets that are the same except for having oppositely ordered properties.  The test dataset in each case is pretty big, to enable time of calculation to be nontrivial, and it is comprised of just a giant square/rectangle of voxel values 1 surrounded by a sea of 0s (C, D and E, below) or some kind of brain mask (G and H, below).  I ran 3dEulerDist in both the default way (multi-ROI-capable functionality), as well as with the faster `-binary_only` case.  The distance is always calculated in *both* the mask and non-mask region (latter given negative distance values).  The test datasets I used below are here:
https://afni.nimh.nih.gov/pub/dist/tgz/tests/test_edt_dimord_ALL.tgz
NB: this directory unpacks to about 1.6GB, even though the compressed tarball is only about 4.2MB, because the 10 dsets therein are each high-dimensional `*.nii` masks (NB: the input NIFTIs are purposefully unzipped, so that wouldn't affect time).

The names of the test dsets and their properties are are given here, with the first 3 numbers being voxel dims, and the next 3 the matrix dimension/lengths):

... C) isotropic matrix dims, differing voxel edges:
```
$ 3dinfo -ad3 -ni -nj -nk -prefix CCC*DSET*
4.000000	2.000000	1.000000	600	600	600	CCC00_DSET.nii
1.000000	2.000000	4.000000	600	600	600	CCC01_DSET.nii
```
... D) differing matrix dims, differing voxel edges:
```
$ 3dinfo -ad3 -ni -nj -nk -prefix DDD*DSET*
4.000000	2.000000	1.000000	500	600	800	DDD00_DSET.nii
1.000000	2.000000	4.000000	800	600	500	DDD01_DSET.nii
```
... E) differing matrix dims, isotropic voxel edges:
```
$ 3dinfo -ad3 -ni -nj -nk -prefix EEE*DSET*
1.000000	1.000000	1.000000	500	600	800	EEE00_DSET.nii
1.000000	1.000000	1.000000	800	600	500	EEE01_DSET.nii

... G) thresholded anatomical brain dset, differing matrix dims, isotropic voxel edges:
$ 3dinfo -ad3 -ni -nj -nk -prefix GGG*DSET*
1.000000	1.000000	1.000000	656	456	256	GGG00_DSET.nii.gz
1.000000	1.000000	1.000000	256	456	656	GGG01_DSET.nii.gz

... H) anatomical GM mask, differing matrix dims, isotropic voxel edges:
$ 3dinfo -ad3 -ni -nj -nk -prefix HHH*DSET*
1.000000	1.000000	1.000000	656	456	256	HHH00_DSET.nii.gz
1.000000	1.000000	1.000000	256	456	656	HHH01_DSET.nii.gz
```

OK, here the paired output times (units of s), with interpretative comments to the right of each pair:
```
dset name (pairs)  binary_only   general     comment

CCC00_DSET.nii          25.738    40.824   -> NO effect for:  
CCC01_DSET.nii          25.484    41.244   -> iso matrix, noniso voxel

DDD00_DSET.nii          28.117    47.164   -> FASTER starting with small dim/large edge:  
DDD01_DSET.nii          35.408    50.208   -> noniso matrix, noniso voxel

EEE00_DSET.nii          26.785    46.059   -> FASTER to start with small dim:
EEE01_DSET.nii          37.066    48.997   -> noniso matrix, iso voxel

GGG00_DSET.nii           7.092     9.479   -> ~FASTER to start with small dim:
GGG01_DSET.nii           8.114    13.042   -> noniso matrix, iso voxel

HHH00_DSET.nii           7.071     8.177   -> FASTER to start with small dim:
HHH01_DSET.nii           9.847    13.777   -> noniso matrix, iso voxel

```

**SO,** the time of execution patterns suggests that *some* speedup might be obtained by going through the axes in order of increasing length: in the many of the (very) anisotropic matrix dimension cases here, the speedup was about 30% in most `-binary_only` cases.  However, in practice with more complicated brain-like datasets that aren't just squares, the speedup benefit might be a bit smaller, and often matrix anisotropy is not so large as in these examples.  I think this ordering matters less when there are not big open patches of either mask or background:  the GGG*DSET* had the least amount of open background (the brain extended nearly across one full dimension), and that is where the smallest percentage increase was observed.

**Comment by neurolabusc** [comment]
@mrneont thanks for your exhaustive testing and explanation. I have cloned your clever solution for anisotropic data. I am closing this issue.

However, if you are interested, niimath makes one optimization not made in AFNI. Specifically, AFNI uses the same function function `run_EDTD_per_line()` for each spatial dimension. In contrast, [niimath](https://github.com/rordenlab/niimath/blob/a2f2d2825c6d1d934d98385d7dfe0b274d8b20e8/src/coreFLT.c#L390) runs `edt1()` for the first dimension, and `edt()` for subsequent dimensions. With the first dimension, you do not need to compare with existing parabolas. If you implement this, the first dimension is faster to calculate than subsequent ones, so I suspect one would have a benefit by processing the longest dimension first. On the other hand, this is an insanely fast algorithm, and the computation time is probably negligible compared to swizzling dimensions to cache and disk I/O. Simpler and easier to maintain code is probably the best choice here.
