### ISSUE TITLE
Install Afni(AFNI_22.0.10) on RHEL 7.9

### ISSUE THREAD

**Issue by sameera2004** [afni/afni#377]
Hello,

I am trying to install Afni (AFNI_22.0.10) on RHEL 7.9 . What is the make file that I should use? I tried Makefile.linux_centos_7_64 and Makefile.linux_openmp_64 and both produced errors. Could you please instruct me to install Afni on our OS?

Thank you 
Sameera

**Comment by sameera2004** [comment]
Thank you @afni-rickr. Now I installed the missing dependencies in other_builds/OS_notes.linux_centos_7.txt. Then I used sudo make -f Makefile.linux_centos_7_64 command and got the following error. 
parser.o:parser.c:(.text+0x99b0): more undefined references to `s_cmp' follow
collect2: error: ld returned 1 exit status
make: *** [LIBMRI_LINUX] Error 1
[parser.c error.txt](https://github.com/afni/afni/files/8701620/parser.c.error.txt)

Please see the attachment for more details. Could you please help me to fix the issue?

**Comment by sameera2004** [comment]
@afni-rickr it worked. We need to use 3dBlurInMask command and I was able to use it without any issue. Thank you very much.

**Comment by afni-rickr** [comment]
That's great to hear, @sameera2004!

**Comment by afni-rickr** [comment]
@sameera2004 The AFNI package is usually installed under a single directory.  For that to be available to multiple users (and since home directories are usually not visible), you would generally move it to a common location, for example /usr/local/afni/bin, or even /usr/local/afni/linux_centos_7_64, in this case.  Using sudo, you could just move your compiled directory there now, and have everyone add that directory to their PATH.
Also, a locally compiled package does not come with atlases and such.  Do you want those?
If so, you could first download the text+atlas package, and then add your compiled binaries to it.  So a more complete set of commands might be (as admin):
`@update.afni.binaries -no_recur -package anyos_text_atlas -bindir /usr/local/afni/linux_centos_7_64`
... and then use 'make' to compile your linux_centos_7_64 binaries ... and then:
`sudo rsync -av linux_centos_7_64/ /usr/local/afni/linux_centos_7_64/`
That last command could be re-run after any compile of a newer package.
Does that seem reasonable?

**Comment by sameera2004** [comment]
@afni-rickr thank you very much it worked now other users can use afni commands. I didn't run the last two commands maybe later I will run them and get more complete set.
