### ISSUE TITLE
Any intent to push to a conda channel?

### ISSUE THREAD

**Issue by effigies** [afni/afni#427]
Hi AFNI team! Just wanted to check in about the status of the conda builds. I know that was something John was working on before he left, and I'm curious if that's been dropped entirely or is just lower on the priority list now.

**Comment by mrneont** [comment]
Hi, Chris-  Since John left for The Real World, we don't have anything under development for this.  There have been various questions about making something for pip installs, for conda installs and for homebrew installs, any of which would be useful.  But it would likely require collaboration with someone else with knowledge in these areas.  At the moment, we don't have the bandwidth for it.

**Comment by effigies** [comment]
Cool. Thanks for the clarification.
