### ISSUE TITLE
SUMA IsoSurface Failed to get volume/data

### ISSUE THREAD

**Issue by vipergabe** [afni/afni#443]
Hi, so I am pretty new when it comes to this program, but I found a page describing how to make an STL surface in AFNI using a binary volume file from Freesurfer. (Link: [)](https://layerfmri.com/2018/07/25/3d-printing-nii-data/) I receive two errors when trying to do this though and I am not sure how to fix it. I input: `IsoSurface -isoval 1 -input aseg_test2.5.mgz -Tsmooth 0.1 100  -remesh 0.5 -overwrite -autocrop -o Output.stl` and it outputs: `--     Error SUMA_Get_isosurface_datasets (SUMA_IsoSurfaceFunc.c:476):
No volume could be had
--     Error IsoSurface (SUMA_IsoSurface.c:537):
Failed to get data.
` If anyone could help with this I would really appreciate it, I am trying to 3-D print a full brain including the cerebellum and stem.

**Comment by mrneont** [comment]
Howdy-

I think the `-input ..` dset should be NIFTI or BRIK/HEAD, not *.mgz format.

If I convert a file called aseg.mgz with:
`@SUMA_FSvolToBRIK aseg.mgz TEST.nii.gz`
... then this works:
`IsoSurface -isorois+dsets -o native.gii -input TEST.nii.gz -noxform -Tsmooth 0.1 100`

Your specific command:
```
IsoSurface                                                                   \
    -isoval     1                                                            \
    -input      TEST.nii.gz                                                  \
    -Tsmooth    0.1 100                                                      \
    -remesh     0.5                                                          \
    -overwrite                                                               \
    -autocrop                                                                \
    -o          Output.stl
```
... still didn't work with the aseg.mgz file I got from the standard `recon-all` output dir mri/, because that dataset apparently had no voxels with a value of 1 (which is what `-isoval 1` masks for).  Instead, this *did* work, because there were some voxels with a value of 10:
```
IsoSurface                                                                   \
    -isoval     10                                                            \
    -input      TEST.nii.gz                                                  \
    -Tsmooth    0.1 100                                                      \
    -remesh     0.5                                                          \
    -overwrite                                                               \
    -autocrop                                                                \
    -o          Output.stl
```

I don't think the value of 1 exists in stanard aparc+aseg FS output.  The cerebellum and brainstem values (both GM and WM) appear to be these values in FS enumeration:
```
7         Left-Cerebellum-White-Matter     
8         Left-Cerebellum-Cortex            
46        Right-Cerebellum-White-Matter       
47        Right-Cerebellum-Cortex             
16        Brain-Stem                           
```

Does this provide you what you want?  This selects out those 5 values from the TEST dataset, though not as a single mask (each value of each ROI piece remains distinct):
```
IsoSurface                                                                   \
    -isorois                                                            \
    -input      TEST.nii.gz'<7,8,16,46,47>'                   \
    -Tsmooth    0.1 100                                                      \
    -remesh     0.5                                                          \
    -overwrite                                                               \
    -autocrop                                                                \
    -o          Output.stl
```

If you wanted to first make simply a binary mask for those 5 regions, and then put that into IsoSurface, you could do this, then:
```
3dcalc -a TEST.nii.gz'<7,8,16,46,47>'  -expr "step(a)" -prefix TEST_MASK.nii.gz 

IsoSurface                                                                   \
    -isorois                                                            \
    -input      TEST_mask_nii.gz                  \
    -Tsmooth    0.1 100                                                      \
    -remesh     0.5                                                          \
    -overwrite                                                               \
    -autocrop                                                                \
    -o          Output_mask.stl
```

**Comment by mrneont** [comment]
(but please also doublecheck that those region numbers are exactly what you want...)

**Comment by vipergabe** [comment]
> (but please also doublecheck that those region numbers are exactly what you want...)

Thank you for the help, I was able to get a few different surface structures with your suggestions, the issue is none of them look correct so I'm guessing I am either using the wrong file to make them or I need to fix the regions I ask for. I need the entire structure including the cerebellum and stem of the brain, I will try adjusting the command to see what I can do to fix this.
