### ISSUE TITLE
AFNI on Docker hub is outdated

### ISSUE THREAD

**Issue by mateuszpawlik** [afni/afni#484]
I don't depend on it but simply observed that the [newest AFNI version on Dockerhub is 22.2.12](https://hub.docker.com/r/afni/afni_make_build/tags).

**Comment by mrneont** [comment]
Ugh, I see.  We appreciate the pointer on that.

That appears to coincide exactly with the time that the macos_build testing started to systematically fail, because some dependency issue started happening on CircleCI.  We looked into it a couple times, but hadn't been able to fix it.

Guess it is time to finally sort that out.  Sigh.

**Comment by mateuszpawlik** [comment]
Have you tried to build it on a local mac os machine? The only error I can find is https://app.circleci.com/pipelines/github/afni/afni/4743/workflows/45fd0550-87cb-478e-a3bc-e53177f8836d/jobs/18119?invite=true#step-103-687 but it doesn't seem to be that problematic.

**Comment by mrneont** [comment]
It seemed that way to us, too.  But "seems" seems to be the key word here!

**Comment by mrneont** [comment]
@mateuszpawlik :  OK, taking a bit of time to play around with this more, this PR:
https://github.com/afni/afni/pull/489
... fixes the underlying macos_build issue, which I think is responsible for scuttling the Docker build.  We will verify whether this is the case at our next build of the binaries.  

But thanks for prompting this re-examination of the framework.

**Comment by mrneont** [comment]
... and indeed, the Docker hub is now updating after that change:
https://hub.docker.com/u/afni

Cheers!
