### ISSUE TITLE
Docker in Linux 22.04

### ISSUE THREAD

**Issue by roohy466** [afni/afni#514]
Hi, I am trying to created the docker images using 22.04 ubuntu, as some softwares might not work with old python version! however a lot of error seems to happen when I am changing the base image! I was wondering have any one created such a afni docker?

**Comment by mrneont** [comment]
Hi-

What version of Python are you using, and what software are you worried might break?  Essentially every AFNI program should work in both Python 2.7 and 3.*.   

Installation instructions for AFNI on Ubuntu 22.04 are here:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu22.html
Those should still work fine.

Re. containers specifically, here are notes on using prebuilt containers, too:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/container.html
Note that we haven't been able to build a container very recently, because we are having issues with CircleCI.

--pt

**Comment by roohy466** [comment]
I do like install antspy beside afni however it needs python 3.7 or above!!!

**Comment by mrneont** [comment]
Hi-  I am not sure I see the problem.  AFNI works with Python 2.7, or 3.* (so, all versions of Python 3).

**Comment by roohy466** [comment]
The problem solved. I was able to add newer python using : 

    RUN add-apt-repository ppa:deadsnakes/ppa &&\
        apt-get update && \
        apt-get install -y \
            python3.10-full \
            python3.10-distutils \
            zsh && \
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && \
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2 && \
        curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
