### ISSUE TITLE
Error while using 3dICC

### ISSUE THREAD

**Issue by hermeckerogg** [afni/afni#72]
Good afternoon AFNI experts.

I'm attempting to look at two different ways to quantify diffusion FA scalars while examining some other factors (e.g. differences across sites and demographic info related to noise), but I get the following error in the output:

Error in `$<-.data.frame`(`*tmp*`, "InputFile", value = character(0)) :
  replacement has 0 rows, data has 630
Calls: $<- -> $<-.data.frame
Execution halted

It looks like an issue with moving between data frames in R but I am unsure of what exactly is wrong. Input file (info redacted) and output file attached.
[ICC_Files_exp.txt](https://github.com/afni/afni/files/1720908/ICC_Files_exp.txt)
[FBIRN_ICC_output.txt](https://github.com/afni/afni/files/1720914/FBIRN_ICC_output.txt)

**Comment by afni-gangc** [comment]
3dICC.R was written a long time ago as a temporary program for computing ICC. A few years ago, the functionality was better implemented as an option -ICC in 3dLME. There is a plan to revamp 3dICC.R so that the most recent methods discussed in the following paper could be incorporated, but that plan has not been materialized yet. So, 3dLME -ICC is currently the preferred the way to go.

Chen, G., Taylor, P.A., Haller, S.P., Kircanski, K., Stoddard, J., Pine, D.S., Leibenluft, E., Brotman, M.A., Cox, R.W., 2017c. Intraclass correlation: improved modeling approaches and applications for neuroimaging. Human Brain Mapping. Human Brain Mapping. DOI: 10.1002/hbm.23909

**Comment by mrneont** [comment]
This seems closeable, because the issue was address by using the more modern program, as noted by @afni-gangc .
